# Generated by Django 4.2.2 on 2023-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classitem',
            new_name='Cartitem',
        ),
    ]
